### ISSUE TITLE
WithMachineName configuration extension method conflict with Serilog.Enrichers.Environment

### ISSUE THREAD

**Issue by Lumirris** [saleem-mirza/serilog-enrichers-context#2]
The `WithMachineName` method in:

[https://github.com/saleem-mirza/serilog-enrichers-context/blob/master/src/Serilog.Enrichers.Context/ContextLoggerConfigurationExtension.cs](https://github.com/saleem-mirza/serilog-enrichers-context/blob/master/src/Serilog.Enrichers.Context/ContextLoggerConfigurationExtension.cs)

has the same signature as in

[https://github.com/serilog/serilog-enrichers-environment/blob/master/src/Serilog.Enrichers.Environment/EnvironmentLoggerConfigurationExtensions.cs](https://github.com/serilog/serilog-enrichers-environment/blob/master/src/Serilog.Enrichers.Environment/EnvironmentLoggerConfigurationExtensions.cs)

This seems to (only recently?) prevent you from using both packages at the same time, because there's an ambiguity build error.

**Comment by saleem-mirza** [comment]
@Lumirris thanks for bringing up this issue. Unfortuntely, it's not easy to modify interface at this time as both packages are being used by community in production environment. However, ugly solution is to not use both packages at same time. Both packages are providing more or less same functionality.

**Comment by tcartwright** [comment]
I know this issue is a bit dated, but another way around the is to just call the extension method directly, like so:

```cs
Serilog.EnvironmentLoggerConfigurationExtensions.WithMachineName(logger.Enrich);
```
OR 
```cs
Serilog.ContextLoggerConfigurationExtension.WithMachineName(logger.Enrich);
```

That way you can still continue to use both libraries.  Posting this for anyone else who comes across this issue.
